import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

import { cn } from "@/lib/utils"
import { Sidenav } from "@/components/sidenav/sidenav";
import { Content } from "@/components/content";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )} flex h-screen bg-zinc-200  justify-center`}>
        <div className="flex w-full px-10 py-20">
          <Sidenav />
          <Content>
            {children}
          </Content>
        </div>

      </body>
    </html>
  );
}
